# EXPERIMENT 2 NUMERICAL PYTHON (NUMPY)

#### Carreos, Christian Benedict R.

#### 2 ECE-C

### NORMALIZATION PROBLEM: 
Normalization is one of the most basic preprocessing techniques in
data analytics. This involves centering and scaling process. Centering means subtracting the data from the
mean and scaling means dividing with its standard deviation. Mathematically, normalization can be
expressed as:
𝑍 = (𝑋 − 𝑥̅)/𝜎
In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and
.std() calls.
In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
ndarray as X_normalized.npy

In [110]:
import numpy as np

# Create a random 5x5 ndarray and store in variable X
X = np.random.rand(5, 5)
X

array([[0.62805082, 0.67966442, 0.85469721, 0.75735638, 0.21063739],
       [0.95097196, 0.61643055, 0.86843073, 0.24156058, 0.43497407],
       [0.36990553, 0.1853921 , 0.30382644, 0.27763142, 0.81711123],
       [0.07694509, 0.66767648, 0.43879162, 0.65286543, 0.46431462],
       [0.636922  , 0.50658183, 0.57890029, 0.38681963, 0.82752994]])

In [112]:
# Normalize X (Subtract X to the mean and divide by the standard deviation)
X_mean = X.mean()
X_std = X.std()
X_normalize = (X - X_mean) / X_std

# Save the normalized ndarray as 'X_normalized.npy'
np.save('X_normalized.npy', X_normalize)

# Print both the 5x5 original ndarray and the normalized ndarray to compare
print("Original 5x5 ndarray X:\n", X)
print("\nNormalized 5x5 ndarray X_normalized:\n", X_normalize)

Original 5x5 ndarray X:
 [[0.62805082 0.67966442 0.85469721 0.75735638 0.21063739]
 [0.95097196 0.61643055 0.86843073 0.24156058 0.43497407]
 [0.36990553 0.1853921  0.30382644 0.27763142 0.81711123]
 [0.07694509 0.66767648 0.43879162 0.65286543 0.46431462]
 [0.636922   0.50658183 0.57890029 0.38681963 0.82752994]]

Normalized 5x5 ndarray X_normalized:
 [[ 0.38348419  0.60173002  1.3418484   0.93024703 -1.38153002]
 [ 1.74894193  0.3343484   1.39991997 -1.25077269 -0.4329323 ]
 [-0.70807174 -1.4882786  -0.98748426 -1.09824872  1.18291777]
 [-1.94684198  0.55103952 -0.41678995  0.48841167 -0.3088671 ]
 [ 0.42099559 -0.13014206  0.17565334 -0.63655121  1.2269728 ]]


## DIVISIBLE BY 3 PROBLEM: Create the following 10 x 10 ndarray.
which are the squares of the first 100 positive integers.
From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy


In [114]:
import numpy as np

# Create a 10x10 ndarray with squares of the first 100 positive integers
A = np.arange(1, 101)**2
A = A.reshape((10, 10))
print (A)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [116]:
# Determine all the elements in the ndarray that are divisible by 3
divisibleby3 = A[A % 3 == 0]

# Save the result as 'div_by_3.npy'
np.save('div_by_3.npy', divisibleby3)

# Print the original 10x10 ndArray and the array of the elements that are divisible by 3
print("10x10 ndarray A (squares of first 100 integers):\n", A)
print("\nElements of A divisible by 3:\n", divisibleby3)

10x10 ndarray A (squares of first 100 integers):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements of A divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
